package me.siwannie.staffhunt.game;

import me.siwannie.staffhunt.StaffHunt;
import me.siwannie.staffhunt.player.PlayerProfile;
import me.siwannie.staffhunt.player.PlayerProfileManager;
import org.bukkit.Bukkit;
import org.bukkit.OfflinePlayer;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.scheduler.BukkitTask;

import java.io.File;
import java.io.IOException;
import java.util.Comparator;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

public class DataManager {

    private final StaffHunt plugin;
    private final PlayerProfileManager profileManager;
    private final GameManager gameManager;
    private BukkitTask savingTask;

    public DataManager(StaffHunt plugin) {
        this.plugin = plugin;
        this.profileManager = plugin.getPlayerProfileManager();
        this.gameManager = plugin.getGameManager();
    }

    public void startPeriodicSaving() { //...
        if (savingTask != null) { //...
            savingTask.cancel(); //...
        }
        long interval = plugin.getConfig().getLong("data-saving.interval-seconds", 60) * 20L; //...
        savingTask = Bukkit.getScheduler().runTaskTimerAsynchronously(plugin, this::saveData, interval, interval); //...
        plugin.getLogger().info("Periodic data saving has started."); //...
    }

    public void stopPeriodicSaving() { //...
        if (savingTask != null) { //...
            savingTask.cancel(); //...
            savingTask = null; //...
            plugin.getLogger().info("Periodic data saving has stopped."); //...
        }
    }

    public void saveData() { //...
        File pointsFile = new File(plugin.getDataFolder(), "points.yml"); //...
        FileConfiguration pointsConfig = new YamlConfiguration(); //...

        // Get ALL hunters from the game, not just online ones
        List<PlayerProfile> hunters = gameManager.getAllHunterUuids().stream()
                .map(profileManager::getProfile)
                .filter(java.util.Objects::nonNull)
                .sorted(Comparator.comparingInt(PlayerProfile::getPoints).reversed())
                .collect(Collectors.toList());

        if (!hunters.isEmpty()) {
            pointsConfig.createSection("hunters"); //...
            int rank = 1; //...
            for (PlayerProfile profile : hunters) {
                String path = "hunters." + profile.getUuid().toString(); //...
                OfflinePlayer player = Bukkit.getOfflinePlayer(profile.getUuid()); //...
                pointsConfig.set(path + ".name", player.getName() != null ? player.getName() : "Unknown"); //...
                pointsConfig.set(path + ".points", profile.getPoints()); //...
                pointsConfig.set(path + ".rank", rank++); //...
            }
        }

        // Get ALL staff from the game, not just online ones
        List<PlayerProfile> staff = gameManager.getAllStaffUuids().stream()
                .map(profileManager::getProfile)
                .filter(java.util.Objects::nonNull)
                .sorted(Comparator.comparingInt(PlayerProfile::getKills).reversed())
                .collect(Collectors.toList());

        if (!staff.isEmpty()) {
            pointsConfig.createSection("staff"); //...
            int rank = 1; //...
            for (PlayerProfile profile : staff) {
                String path = "staff." + profile.getUuid().toString(); //...
                OfflinePlayer player = Bukkit.getOfflinePlayer(profile.getUuid()); //...
                pointsConfig.set(path + ".name", player.getName() != null ? player.getName() : "Unknown"); //...
                pointsConfig.set(path + ".kills", profile.getKills()); //...
                pointsConfig.set(path + ".rank", rank++); //...
            }
        }

        // Save the config to file
        // This is wrapped in a sync task to ensure thread safety with Bukkit's saving methods if needed
        Bukkit.getScheduler().runTask(plugin, () -> { //...
            try {
                pointsConfig.save(pointsFile); //...
            } catch (IOException e) {
                plugin.getLogger().severe("Could not save points.yml!"); //...
                e.printStackTrace(); //...
            }
        });
    }
}